# Generated by Django 6.0 on 2025-12-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to='plans.week')),
            ],
        ),
    ]
