# Generated by Django 6.0 on 2025-12-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_diet"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="workout_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="week",
            name="diet_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
