# Generated by Django 6.0 on 2025-12-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Alumno'), ('ADMIN', 'Administrador'), ('ROOT', 'Root')], default='STUDENT', max_length=20),
        ),
    ]
